import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ActivityIndicator, Text, View } from "react-native";
import { useGetPing } from "@odyssey/api-client";

const queryClient = new QueryClient();

function PingScreen() {
  // useGetPing is generated by Orval from the backend OpenAPI contract.
  // Nothing here is hand-typed — the Ping shape comes from the generated types.
  const { data, isLoading, error } = useGetPing();

  return (
    <View
      style={{
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        gap: 12,
      }}
    >
      <Text style={{ fontSize: 20, fontWeight: "600" }}>Odyssey pipeline spike</Text>
      {isLoading ? (
        <ActivityIndicator />
      ) : error ? (
        <Text style={{ color: "red" }}>Error: {String(error)}</Text>
      ) : (
        <Text>
          /ping → id={data?.id} message={data?.message}
        </Text>
      )}
    </View>
  );
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <PingScreen />
    </QueryClientProvider>
  );
}
